Use wkhtmltopdf instead of phantomjs to create PDF files.
microluxe20/microluxe20 pull request #60
Opened 2019-05-03 00:44 UTC by Web-eWorks

Move away from phantomJS for generating our PDF files - there are a number of issues enumerated in #59. I'm too tired to fill out the description; just read the diff if you want to know what it does.

2019-10-03 08:11 UTC, Web-eWorks commented on src/lib/transformer.js
> +function generateTableBody(data, rows, columns) {
I will not be further refactoring this function. It is already *dead* simple, with well-named variables.

2019-10-03 08:44 UTC, Web-eWorks commented
Pinging @kgrubb; this is (FINALLY!) ready for primetime.

Give it a look over, and please, please kick the Cognitive Complexity on codeclimate up to 10. One tightly-optimized double-loop is still 10 CC for some reason.

2019-10-04 19:42 UTC, kgrubb commented
for the cognitive complexity, you'll need to update the codeclimate.yml file with something like this:

```yml
version: "2"
checks:
  method-lines:
      config:
        threshold: 35
  method-complexity:
    config:
      threshold: 10
```

2019-10-05 22:32 UTC, Web-eWorks commented
Commit history has been cleaned up. Ready when you are.

2019-10-30 01:25 UTC, kgrubb commented
Can we get some new docs on requirements for contributing? It looks like installing wkhtml2pdf via apt on ubuntu 18.04 isn't sufficient, and I haven't tried on my macOS pc yet, but I'm assuming things will fail if wkhtml2pdf isn't installed locally.

2020-11-26 16:53 UTC, Web-eWorks commented
So... eleven force-pushes later, this is ready to go. For the record, the default CI image already has `node:lts` installed, and it's *so much easier* to install packages in it instead of through the Docker image.

You can actually download and take a look at the built Microluxe20 PDFs right [here](https://github.com/Web-eWorks/microluxe20/runs/1460062522) from the workflow run on my repo - I reconfigured the release script to handle CI as well. I think this capability **more** than satisfies any concerns about whether contributors will be able to use `wkhtmltopdf`?

2020-11-30 00:01 UTC, kgrubb requested changes
just have 2 quick points to review. This is looking great! I've already made the changes locally and rebuilt the documents and everything looks awesome. and no more phantomjs! :tada:

2020-11-30 00:01 UTC, kgrubb commented on src/markdown/microluxe20_lore.md
The markdown files with `$header-main` are failing to generate things properly. Looks like they just need to be swapped to `$header` instead of `$header-main`

2020-11-30 00:10 UTC, Web-eWorks commented on src/lib/html-to-pdf.js
> +const fs = pify(require('fs'));
It's only been... what, a year and a half since I wrote this? :stuck_out_tongue: Will do, glad to see that I don't need to add another module.

2020-11-30 00:13 UTC, Web-eWorks commented on src/markdown/microluxe20_lore.md
Will look into that; `$header-main` is meant to display the front page of a document with the Microluxe20 logo image, if that's failing to generate properly it might be an issue with the logo file instead. IIRC I actually do want to keep `$header-main` separate...

2020-11-30 00:31 UTC, Web-eWorks commented on src/markdown/microluxe20_lore.md
Yeah, looking into it, `$header` is disabled in "unity" builds, whereas `$header-main` is for situations in which we explicitly want to keep the logo and text generation (e.g. for the first document) in a unity build. I was unable to reproduce any errors with the build process, so please post your error logs or a copy of the malformed PDF so I can look into it!

2020-11-30 00:36 UTC, kgrubb approved these changes

2020-11-30 00:36 UTC, merged